apiVersion: v1
kind: ServiceAccount
metadata:
  name: loadgen-scaler
  namespace: prombench-{{ .PR_NUMBER }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prombench-{{ .PR_NUMBER }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: prombench-{{ .PR_NUMBER }}
  labels:
    app: promtail