apiVersion: v1
kind: Secret
metadata:
  name: hmac-token
type: Opaque
data:
  hmac: "{{ .HMAC_TOKEN }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-token
type: Opaque
data:
  oauth: "{{ .OAUTH_TOKEN }}"
